spring:
  application:
    name: spring-cloud-user-feign-hystrix-dashborad


# 将当前服务注册到eureka的核心配置
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true  #使用ip地址


server:
  port: 8300

feign:
  hystrix:
    enabled: true  #开启feign基于hystrix服务容错功能


#management:
#  security:
#    enabled: false
#management:
#  endpoints:
#    web:
#      exposure:
management:
  endpoints:
    web:
      exposure:
        include: '*'
#        include: *